replicaCount: 1

image:
  repository: registry.cn-hangzhou.aliyuncs.com/viking602/uv-ubuntu
  tag: "1.0.1"
  pullPolicy: IfNotPresent

pvc:
  storageClassName: ""
  storage: 50Gi

service:
  type: ClusterIP
  port: 8888

pythonVersion: "3.12"

securityContext:
  allowPrivilegeEscalation: true
  privileged: true

password: "jupyter"

resources: {}
  # limits:
  #   cpu: "500m"
  #   memory: "1Gi"
  # requests:
  #   cpu: "200m"
  #   memory: "512Mi"

nodeSelector: {}
tolerations: []
affinity: {}